services:
  slides-frontend:
    image: ghcr.io/crqch/slides-frontend:latest
    container_name: slides-frontend
    expose:
      - 3000
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000']
      interval: 30s
      timeout: 10s
      retries: 3
