const code0 = {
	html: [
		'<!doctype html>\n<!-- Niektóre przeglądarki są bardzo stare, musimy im czasami pomóc zrozumieć że to jest dokument HTML. -->',
		'<!doctype html>\n<html> <!-- korzeń dokumentu HTML -->\n\n</html>',
		'<!doctype html>\n<html>\n<!-- jedynymi dziećmi tagu html powinny być head i body -->\n\n<head>\n</head>\n\n<body>\n</body>\n\n</html>',
		'<!doctype html>\n<html lang="pl"> <!-- możemy ustawić język dokumentu, to pomaga narzędziom TTS lub tłumaczom -->\n\n<head>\n</head>\n\n<body>\n</body>\n\n</html>',
		'<!doctype html>\n<html lang="pl">\n\n<head>\n    <!-- Tutaj konfigurujemy metadane dokumentu -->\n</head>\n\n<body>\n</body>\n\n</html>',
		'<!doctype html>\n<html lang="pl">\n\n<head>\n    <title>Moja pierwsza strona</title>\n</head>\n\n<body>\n</body>\n\n</html>',
		'<!doctype html>\n<html lang="pl">\n\n<head>\n    <title>Moja pierwsza strona</title>\n    <link rel="stylesheet" href="default.css">\n    <link rel="stylesheet alternate" href="alt.css">\n    <script src="app.js"></script>\n    <meta name="application-name" content="Tautinder">\n    <meta name="application-desc" content="Poznaj nowych informatyków w twojej okolicy">\n</head>\n\n<body>\n</body>\n\n</html>',
		'<!doctype html>\n<html lang="pl">\n\n<head>\n    <title>Moja pierwsza strona</title>\n</head>\n\n<body>\n    <!-- Tutaj deklarujemy elementy dokumentu -->\n</body>\n\n</html>',
		'<!doctype html>\n<html lang="pl">\n\n<head>\n    <title>Moja pierwsza strona</title>\n</head>\n\n<body>\n    <h1>Tautinder</h1>\n</body>\n\n</html>',
		'<!doctype html>\n<html lang="pl">\n\n<head>\n    <title>Moja pierwsza strona</title>\n</head>\n\n<body>\n    <h1>Tautinder</h1>\n    <p>Poznaj nowych informatyków w twojej okolicy</p>\n</body>\n\n</html>',
		'<!doctype html>\n<html lang="pl">\n\n<head>\n    <title>Moja pierwsza strona</title>\n</head>\n\n<body>\n    <h1>Tautinder</h1>\n    <p>Poznaj nowych informatyków w twojej okolicy</p>\n    <button>Poznaj!</button>\n</body>\n\n</html>',
		'<!doctype html>\n<html lang="pl">\n\n<head>\n    <title>Moja pierwsza strona</title>\n</head>\n\n<body>\n    <h1>Tautinder</h1>\n    <p>Poznaj nowych informatyków w twojej okolicy</p>\n    <button>Poznaj!</button>\n\n    <p>Uwaga. Nie gwarantujemy poprawności działania algorytmu poznawania.</p>\n</body>\n\n</html>',
		'<!doctype html>\n<html lang="pl">\n\n<head>\n    <title>Moja pierwsza strona</title>\n</head>\n\n<body>\n    <h1>Tautinder</h1>\n    <p>Poznaj nowych informatyków w twojej okolicy</p>\n    <button>Poznaj!</button>\n\n    <p>Uwaga. <b>Nie</b> gwarantujemy poprawności działania algorytmu poznawania.</p>\n</body>\n\n</html>',
		'<!doctype html>\n<html lang="pl">\n\n<head>\n    <title>Moja pierwsza strona</title>\n</head>\n\n<body>\n    <h1>Tautinder</h1>\n    <p>Poznaj nowych informatyków w twojej okolicy</p>\n    <button>Poznaj!</button>\n\n    <p>Uwaga. <b>Nie</b> gwarantujemy poprawności działania algorytmu poznawania.</p>\n\n    <hr>\n</body>\n\n</html>',
		'<!doctype html>\n<html lang="pl">\n\n<head>\n    <title>Moja pierwsza strona</title>\n</head>\n\n<body>\n    <h1>Tautinder</h1>\n    <p>Poznaj nowych informatyków w twojej okolicy</p>\n    <button>Poznaj!</button>\n\n    <p>Uwaga. <b>Nie</b> gwarantujemy poprawności działania algorytmu poznawania.</p>\n\n    <hr>\n\n    <footer>\n        <a href="/regulamin">Regulamin</a>\n        <a href="/privacy-policy">Polityka prywatności</a>\n    </footer>\n</body>\n\n</html>',
		'<!doctype html>\n<html lang="pl">\n\n<head>\n    <title>Moja pierwsza strona</title>\n</head>\n\n<body>\n    <nav style="display: flex; flex-direction: row; justify-content: space-between; width: 100%;">\n        <b>Tautinder</b>\n        <button>Zaloguj się</button>\n    </nav>\n    <p>Poznaj nowych informatyków w twojej okolicy</p>\n    <button>Poznaj!</button>\n\n    <p>Uwaga. <b>Nie</b> gwarantujemy poprawności działania algorytmu poznawania.</p>\n\n    <hr>\n\n    <footer>\n        <a href="/regulamin">Regulamin</a>\n        <a href="/privacy-policy">Polityka prywatności</a>\n    </footer>\n</body>\n\n</html>',
		'<!doctype html>\n<html lang="pl">\n\n<head>\n    <title>Moja pierwsza strona</title>\n</head>\n\n<body>\n    <nav style="display: flex; flex-direction: row; justify-content: space-between; width: 100%;">\n        <b>Tautinder</b>\n        <button>Zaloguj się</button>\n    </nav>\n    <hr>\n    <p>Poznaj nowych informatyków w twojej okolicy</p>\n    <button>Poznaj!</button>\n\n    <p>Uwaga. <b>Nie</b> gwarantujemy poprawności działania algorytmu poznawania.</p>\n\n    <hr>\n\n    <footer>\n        <a href="/regulamin">Regulamin</a>\n        <a href="/privacy-policy">Polityka prywatności</a>\n    </footer>\n</body>\n\n</html>',
		'<!doctype html>\n<html lang="pl">\n\n<head>\n    <title>Moja pierwsza strona</title>\n</head>\n\n<body>\n    <nav style="display: flex; flex-direction: row; justify-content: space-between; width: 100%;">\n        <b>Tautinder</b>\n        <button>Zaloguj się</button>\n    </nav>\n    <hr>\n    <p>Poznaj nowych informatyków w twojej okolicy</p>\n    <button>Poznaj!</button>\n\n    <p>Uwaga. <b>Nie</b> gwarantujemy poprawności działania algorytmu poznawania.</p>\n\n    <p>Benefity korzystania z programu:</p>\n    <ul>\n\n    </ul>\n\n    <hr>\n\n    <footer>\n        <a href="/regulamin">Regulamin</a>\n        <a href="/privacy-policy">Polityka prywatności</a>\n    </footer>\n</body>\n\n</html>',
		'<!doctype html>\n<html lang="pl">\n\n<head>\n    <title>Moja pierwsza strona</title>\n</head>\n\n<body>\n    <nav style="display: flex; flex-direction: row; justify-content: space-between; width: 100%;">\n        <b>Tautinder</b>\n        <button>Zaloguj się</button>\n    </nav>\n    <hr>\n    <p>Poznaj nowych informatyków w twojej okolicy</p>\n    <button>Poznaj!</button>\n\n    <p>Uwaga. <b>Nie</b> gwarantujemy poprawności działania algorytmu poznawania.</p>\n\n    <p>Benefity korzystania z programu:</p>\n    <ul>\n        <li>Kryzys wieku średniego</li>\n        <li>Łysina</li>\n    </ul>\n\n    <hr>\n\n    <footer>\n        <a href="/regulamin">Regulamin</a>\n        <a href="/privacy-policy">Polityka prywatności</a>\n    </footer>\n</body>\n\n</html>'
	]
};

export { code0 };
